DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): raw.githubusercontent.com:443
DEBUG:urllib3.connectionpool:https://raw.githubusercontent.com:443 "GET /asadas1/ExcelToCal-Python/master/version.txt HTTP/1.1" 200 109
DEBUG:requests_oauthlib.oauth2_session:Generated new state QIP7670myXVvyoj3JZONzkT5D9vYfE.
INFO:google_auth_oauthlib.flow:"GET /?state=QIP7670myXVvyoj3JZONzkT5D9vYfE&code=4/2QGQqo1QJwKc5WmlyIhkbmXOe1vvqvCRnoI7dScmQ3LZh2ygV4ECp_D2Rux09ytDlCYLK5L6rUCbT5wlPpcKLko&scope=https://www.googleapis.com/auth/calendar%20https://www.googleapis.com/auth/spreadsheets%20https://www.googleapis.com/auth/drive HTTP/1.1" 200 65
DEBUG:requests_oauthlib.oauth2_session:Encoding `client_id` "684343053641-6o79kfodd569mo60qr90nnp3a9n3fqi9.apps.googleusercontent.com" with `client_secret` as Basic auth credentials.
DEBUG:requests_oauthlib.oauth2_session:Requesting url https://oauth2.googleapis.com/token using method POST.
DEBUG:requests_oauthlib.oauth2_session:Supplying headers {'Accept': 'application/json', 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'} and data {'grant_type': 'authorization_code', 'code': '4/2QGQqo1QJwKc5WmlyIhkbmXOe1vvqvCRnoI7dScmQ3LZh2ygV4ECp_D2Rux09ytDlCYLK5L6rUCbT5wlPpcKLko', 'redirect_uri': 'http://localhost:51990/'}
DEBUG:requests_oauthlib.oauth2_session:Passing through key word arguments {'timeout': None, 'auth': <requests.auth.HTTPBasicAuth object at 0x04688F10>, 'verify': True, 'proxies': None}.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): oauth2.googleapis.com:443
DEBUG:urllib3.connectionpool:https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None
DEBUG:requests_oauthlib.oauth2_session:Request to fetch token completed with status 200.
DEBUG:requests_oauthlib.oauth2_session:Request url was https://oauth2.googleapis.com/token
DEBUG:requests_oauthlib.oauth2_session:Request headers were {'User-Agent': 'python-requests/2.24.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8', 'Content-Length': '173', 'Authorization': 'Basic Njg0MzQzMDUzNjQxLTZvNzlrZm9kZDU2OW1vNjBxcjkwbm5wM2E5bjNmcWk5LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tOkxMUFVkOFNVc25lU2NnOWdLeFpnbGtIYQ=='}
DEBUG:requests_oauthlib.oauth2_session:Request body was grant_type=authorization_code&code=4%2F2QGQqo1QJwKc5WmlyIhkbmXOe1vvqvCRnoI7dScmQ3LZh2ygV4ECp_D2Rux09ytDlCYLK5L6rUCbT5wlPpcKLko&redirect_uri=http%3A%2F%2Flocalhost%3A51990%2F
DEBUG:requests_oauthlib.oauth2_session:Response headers were {'Content-Type': 'application/json; charset=utf-8', 'Vary': 'Origin, X-Origin, Referer', 'Content-Encoding': 'gzip', 'Date': 'Thu, 23 Jul 2020 21:26:49 GMT', 'Server': 'scaffolding on HTTPServer2', 'Cache-Control': 'private', 'X-XSS-Protection': '0', 'X-Frame-Options': 'SAMEORIGIN', 'X-Content-Type-Options': 'nosniff', 'Alt-Svc': 'h3-29=":443"; ma=2592000,h3-27=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"', 'Transfer-Encoding': 'chunked'} and content {
  "access_token": "ya29.a0AfH6SMDzdwT50uhG8Wf4YHphc7lhQbjpObe-tYGgAFg9-HsNEs3SMtusX0l_8UOlCB7Fweyt6WxHuLGtGV4sxKvWk2cloRGcTaZIbEMHaNGukudUxaPc9IL1sRfNAFwerUcFuxhkRZCVlKeaN240QaIB4Q0ErM-6rJE",
  "expires_in": 3599,
  "refresh_token": "1//0fRkVzdBWSnCUCgYIARAAGA8SNwF-L9IrvLCOjxtUblDVjN4aH11T17kZHPdyqGUqMW7xaEukwPubU2qiiIBAF7pkI_aa7Gnb6Jw",
  "scope": "https://www.googleapis.com/auth/drive https://www.googleapis.com/auth/calendar https://www.googleapis.com/auth/spreadsheets",
  "token_type": "Bearer"
}.
DEBUG:requests_oauthlib.oauth2_session:Invoking 0 token response hooks.
DEBUG:requests_oauthlib.oauth2_session:Obtained token {'access_token': 'ya29.a0AfH6SMDzdwT50uhG8Wf4YHphc7lhQbjpObe-tYGgAFg9-HsNEs3SMtusX0l_8UOlCB7Fweyt6WxHuLGtGV4sxKvWk2cloRGcTaZIbEMHaNGukudUxaPc9IL1sRfNAFwerUcFuxhkRZCVlKeaN240QaIB4Q0ErM-6rJE', 'expires_in': 3599, 'refresh_token': '1//0fRkVzdBWSnCUCgYIARAAGA8SNwF-L9IrvLCOjxtUblDVjN4aH11T17kZHPdyqGUqMW7xaEukwPubU2qiiIBAF7pkI_aa7Gnb6Jw', 'scope': ['https://www.googleapis.com/auth/drive', 'https://www.googleapis.com/auth/calendar', 'https://www.googleapis.com/auth/spreadsheets'], 'token_type': 'Bearer', 'expires_at': 1595543207.7407432}.
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "site-packages\googleapiclient\discovery_cache\__init__.py", line 36, in autodetect
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\googleapiclient\discovery_cache\file_cache.py", line 33, in <module>
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\googleapiclient\discovery_cache\file_cache.py", line 37, in <module>
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\googleapiclient\discovery_cache\__init__.py", line 42, in autodetect
  File "c:\users\the real sauce boss\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\googleapiclient\discovery_cache\file_cache.py", line 41, in <module>
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/discovery/v1/apis/calendar/v3/rest
DEBUG:urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.googleapis.com:443
DEBUG:urllib3.connectionpool:https://www.googleapis.com:443 "GET /drive/v3/files?q=mimeType%3D%22application%2Fvnd.google-apps.spreadsheet%22+and+name+%3D+%22Nexus+Recording+Schedule+-+Master%22&pageSize=1000&supportsAllDrives=True&includeItemsFromAllDrives=True HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): sheets.googleapis.com:443
DEBUG:urllib3.connectionpool:https://sheets.googleapis.com:443 "GET /v4/spreadsheets/15-sqH2xXxN2Oq-VPR-Ei7u9aUIqImjEMFieo32gd1BQ?includeGridData=false HTTP/1.1" 200 None
INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/calendar/v3/users/me/calendarList?alt=json
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "site-packages\googleapiclient\discovery_cache\__init__.py", line 36, in autodetect
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\googleapiclient\discovery_cache\file_cache.py", line 33, in <module>
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\googleapiclient\discovery_cache\file_cache.py", line 37, in <module>
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\googleapiclient\discovery_cache\__init__.py", line 42, in autodetect
  File "c:\users\the real sauce boss\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\googleapiclient\discovery_cache\file_cache.py", line 41, in <module>
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/discovery/v1/apis/sheets/v4/rest
INFO:googleapiclient.discovery:URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/15-sqH2xXxN2Oq-VPR-Ei7u9aUIqImjEMFieo32gd1BQ/values/1-Approve%20Courses-Instructors-DropDown%20Menus%21N2%3AAN799?alt=json
INFO:googleapiclient.discovery:URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/15-sqH2xXxN2Oq-VPR-Ei7u9aUIqImjEMFieo32gd1BQ/values/2-Schedule%20Recording-Instructional%20Day%21A57%3AAA?alt=json
DEBUG:urllib3.connectionpool:https://sheets.googleapis.com:443 "PUT /v4/spreadsheets/15-sqH2xXxN2Oq-VPR-Ei7u9aUIqImjEMFieo32gd1BQ/values/%272-Schedule%20Recording-Instructional%20Day%27%21Z308?valueInputOption=USER_ENTERED HTTP/1.1" 200 None
INFO:googleapiclient.discovery:URL being requested: POST https://www.googleapis.com/calendar/v3/calendars/umich.edu_43687279736c65725f31303942%40resource.calendar.google.com/events?sendUpdates=all&alt=json
